describe('Checks Game', function(){
    beforeEach(()=>{cy.visit('/')})
    it('Checks greeting', function(){
        cy.contains('Welcome to Rock, Paper, Scissors')
    })
    it('Check buttons displayed', function(){
        cy.get('#name').type('Lewis')
        cy.get('#submit').click()
        cy.url().should('include', '/easyHard')
        cy.get('#easy').click()
        cy.get('#rock')
        cy.get('#paper')
        cy.get('#scissors')
        cy.url().should('include', '/game')
    })
     it('Check buttons displayed', function(){
        cy.get('#name').type('Lewis')
        cy.get('#submit').click()
        cy.get('#hard').click()
        cy.get('#rock')
        cy.get('#paper')
        cy.get('#scissors')
        cy.get('#lizard')
        cy.get('#spock')
        cy.url().should('include', '/game')
    })
    it('Check button click correct', function(){
        cy.get('#name').type('Lewis')
        cy.get('#submit').click()
        cy.get('#easy').click()
        cy.get('#rock').click()
        cy.get('#player-choice').contains('Rock')
        cy.get('#player-name').contains('Lewis')
        cy.url().should('include', '/conf')
    })
    it('Check play again button', function(){
        cy.get('#name').type('Lewis')
        cy.get('#submit').click()
        cy.get('#easy').click()
        cy.get('#rock').click()
        cy.get('#play-again').click()
        cy.url().should('include', '/playAgain')
        cy.get('#rock').click()
        cy.url().should('include', '/conf')
    })
    it('Change game settings link works', function(){
        cy.get('#name').type('Lewis')
        cy.get('#submit').click()
        cy.get('#easy').click()
        cy.get('#rock').click()
        cy.get('#settings').click()
        cy.get('#easy')
        cy.url().should('include', '/easyHard')
        cy.get('#hard').click()
        cy.get('#settings').click()
        cy.get('#easy')
        cy.get('#hard')
        cy.url().should('include', '/easyHard')
    })
    it('Check correct results are displayed', function(){
        cy.get('#name').type('Lewis')
        cy.get('#submit').click()
        cy.get('#easy').click()
        cy.get('#rock').click()
        cy.get('#computer-choice')
            .then(function(val){
                let value=val[0].innerHTML
                if (value==='Rock'){
                    cy.get('#message').contains('Draw')
                    cy.get('#player-tally').contains('0')
                    cy.get('#comp-tally').contains('0')
                } else if (value==='Scissors'){
                    cy.get('#message').contains('Player Wins')
                    cy.get('#player-tally').contains('1')
                    cy.get('#comp-tally').contains('0')
                } else if (value==='Paper'){
                    cy.get('#message').contains('Computer Wins')
                    cy.get('#player-tally').contains('0')
                    cy.get('#comp-tally').contains('1')
                } else {
                    expect(true).to.equal(false)
                }
            })
    })
})